dependencies:
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
    - aave/protocol-v2@1.0.1
compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
            - "@aave=aave/protocol-v2@1.0.1"

dotenv: .env
# Change to trye to verify smart contracts
verify: False
# set a custom mnemonic for the development network

networks:
    default: mainnet-fork
    mainnet-fork:
      weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
      lending_pool_provider: "0xb53c1a33016b2dc2ff3653530bff1848a515c8c5"
    goerli:
      weth_token: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
      lending_pool_provider: "0x5E52dEc931FFb32f609681B8438A51c675cc232d"
wallets:
  from_key: ${PRIVATE_KEY}

